### ISSUE TITLE
Card sizes dont match those in figma

### ISSUE THREAD

**Issue by oveddan** [itpresidents/thesis-archive-2020#63]
[If we go to the DesignSystem tab of Figma,](https://www.figma.com/file/oUFvZ5S1zSGRettExkwGuT/Thesis-Website-2020?node-id=111%3A300) we can see there are two sizes for the cards, one for desktop and one for mobile:

<img width="852" alt="Screen Shot 2020-04-26 at 10 33 10 PM" src="https://user-images.githubusercontent.com/891755/80337104-ed92e180-880d-11ea-8026-71bdb440a41f.png">

## On desktop

Card outer size should be, 212x395:

<img width="102" alt="Screen Shot 2020-04-26 at 10 33 26 PM" src="https://user-images.githubusercontent.com/891755/80337132-01d6de80-880e-11ea-985a-5ff52a5ac1d1.png">

Card image size should be 212x300:

<img width="182" alt="Screen Shot 2020-04-26 at 10 34 20 PM" src="https://user-images.githubusercontent.com/891755/80337176-19ae6280-880e-11ea-9590-3b9fafef5511.png">

On Mobile

Card Size outer should be 175.5x327

<img width="120" alt="Screen Shot 2020-04-26 at 10 37 55 PM" src="https://user-images.githubusercontent.com/891755/80337402-98a39b00-880e-11ea-8af7-134dbdac3e55.png">

Card inner size 175.5x248.35

<img width="134" alt="Screen Shot 2020-04-26 at 10 36 50 PM" src="https://user-images.githubusercontent.com/891755/80337368-86c1f800-880e-11ea-8798-8a5421a59fae.png">

**Comment by EonYang** [comment]
Fixed~~~
