### ISSUE TITLE
abstract section ignores line breaks and paragraphs

### ISSUE THREAD

**Issue by noisyneuron** [itpresidents/thesis-archive-2020#68]
paragraphs created through the rich text editor don't make it to the front end; 
html `<br>` tags render as normal text, so that doesn't work as a solution either

**Comment by EonYang** [comment]
Can you share a link in which I can repeat this problem? Thanks!

**Comment by noisyneuron** [comment]
Yep -- https://thesis-archive-2020.netlify.app/students/25
You'll see `<br><br>` in the text -- on the backend, there is a new paragraph starting there, but it doesn't render. And the HTML is escaped, so the `<br>` doesn't work either.

In the inspector, you can see where there should have been paragraphs --
![Screen Shot 2020-04-30 at 3 24 23 PM](https://user-images.githubusercontent.com/1571964/80750800-b9157300-8af6-11ea-8dd4-a1878542bbc8.png)

**Comment by EonYang** [comment]
Thank you so much! Fixed!
