### ISSUE TITLE
image captions aren't rendered

### ISSUE THREAD

**Issue by noisyneuron** [itpresidents/thesis-archive-2020#70]
captions inserted through the wordpress interface (along with alt text) are not rendered:
```
<figure class="figure">
   <img width="100%" alt="Lines of code that look like poetry, along with the colorful visual output they create." 
   src="https://itp.nyu.edu/thesis2020/wp-content/uploads/2020/04/august-1024x576.png"
   class="figure-img img-fluid">
   <figcaption class="figure-caption"> CAPTION_SHOULD_APPEAR_HERE </figcaption>
</figure>

**Comment by EonYang** [comment]
Thank you so much for QAing. Fixed.

**Comment by noisyneuron** [comment]
@EonYang this is still not working.. I added the caption as part of the image fields (see screenshot) - but it doesn't render [here](https://thesis-archive-2020.netlify.app/students/25)

<img width="297" alt="Screen Shot 2020-05-01 at 10 46 22 AM" src="https://user-images.githubusercontent.com/1571964/80814017-1e21a500-8b99-11ea-8cbc-f9068a1458ef.png">

**Comment by EonYang** [comment]
I think it’s showing up.

The server needs sometime to server new content I guess.



Yang Yang
ITP Post-Doctoral Fellow
ITP/TSOA/NYU
Portfolio, Linkedin
yy2473@nyu.edu
718-3603-754
