### ISSUE TITLE
rich text fields don't allow embeds

### ISSUE THREAD

**Issue by noisyneuron** [itpresidents/thesis-archive-2020#71]
Unable to embed images and videos in rich text fields. The research section in [this post](https://thesis-archive-2020.netlify.app/students/25) shows the raw html content. Need to be able to insert images into relevant areas of text so they are not out of context

**Comment by EonYang** [comment]
@oveddan can you look at this?

**Comment by EonYang** [comment]
Theoretically fixed. Please let me know if I did it incorrectly.

**Comment by EonYang** [comment]
It's up and looks great. Closed for now.
