### ISSUE TITLE
text encoding on homepage

### ISSUE THREAD

**Issue by noisyneuron** [itpresidents/thesis-archive-2020#73]
apostrophe / quotes aren't rendered (works fine on project pages)
<img width="242" alt="Screen Shot 2020-04-30 at 3 18 57 PM" src="https://user-images.githubusercontent.com/1571964/80750437-15c45e00-8af6-11ea-979d-ac6811c49c10.png">

**Comment by EonYang** [comment]
Thanks! fixed!
