### ISSUE TITLE
"image through text" 4 & 5 don't render

### ISSUE THREAD

**Issue by noisyneuron** [itpresidents/thesis-archive-2020#75]
the first 3 images show up at various points of the text, but the 4th and 5th don't render anywhere... I'm guessing this should be right at the end, after "further reading"? 

_[ i think this is the last issue i see -- thanks @EonYang and @oveddan for speedily taking care of things! :) ]_

**Comment by oveddan** [comment]
Fixed 8433f56dbff06d0a750ea5fd3d092bbca8d46c52
