### ISSUE TITLE
cors issue on itp.nyu.edu/thesis2020

### ISSUE THREAD

**Issue by noisyneuron** [itpresidents/thesis-archive-2020#86]
Error message: Access to manifest at 'https://itpthesis2020.site/manifest.json' from origin 'https://itp.nyu.edu' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by oveddan** [comment]
Spent a while debugging this.  CORS was enabled, but I believe that the scripts it was pulling no longer existed once we pushed new code to netlify.  We need to consider what happens when we push to master.  maybe we dont push to master

**Comment by oveddan** [comment]
Same issue occurs now if I try to preview a deploy of a previous version.  I need to tell netlify to keep old files around.

**Comment by oveddan** [comment]
https://community.netlify.com/t/keep-js-chunks-from-old-deploys/5991

**Comment by oveddan** [comment]
Ive turned off auto-publishing in netlify.
